---

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells:

#---------------------------------------SDI MATRICES----------------------------------------------
  BMMatrixHealth_gl-ep-bxl-jan-mtx01:
    dataRef: "availability gl-ep-bxl-jan-mtx01"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-bxl-jan-mtx02:
    dataRef: "availability gl-ep-bxl-jan-mtx02"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-bxl-jan-mtx03:
    dataRef: "availability gl-ep-bxl-jan-mtx03"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-bxl-jan-mtx04:
    dataRef: "availability gl-ep-bxl-jan-mtx04"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-bxl-phs-hem-mtx01:
    dataRef: "availability gl-ep-bxl-phs-hem-mtx01"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-bxl-phs-hem-mtx02:
    dataRef: "availability gl-ep-bxl-phs-hem-mtx02"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-stb-hem-mtx01:
    dataRef: "availability gl-ep-stb-hem-mtx01"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }
  BMMatrixHealth_gl-ep-stb-hem-mtx02:
    dataRef: "availability gl-ep-stb-hem-mtx02"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 99 }

#-------------------------------------------ENCODERS----------------------------------------------
  encoderHealth_gl-ep-bxl-jan-avpu01:
    dataRef: Health gl-ep-bxl-jan-avpu01
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-bxl-jan-avpu01:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-bxl-jan-avpu01&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-bxl-jan-avpu02:
    dataRef: Health gl-ep-bxl-jan-avpu02
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-bxl-jan-avpu02:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-bxl-jan-avpu02&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-bxl-jan-avpu03:
    dataRef: Health gl-ep-bxl-jan-avpu03
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-bxl-jan-avpu03:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-bxl-jan-avpu03&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-bxl-jan-avpu04:
    dataRef: Health gl-ep-bxl-jan-avpu04
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-bxl-jan-avpu04:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-bxl-jan-avpu04&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-bxl-phs-hem-avpu01:
    dataRef: Health gl-ep-bxl-phs-hem-avpu01
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-bxl-phs-hem-avpu01:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-bxl-phs-hem-avpu01&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-bxl-phs-hem-avpu02:
    dataRef: Health gl-ep-bxl-phs-hem-avpu02
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-bxl-phs-hem-avpu02:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-bxl-phs-hem-avpu02&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-stb-hem-avpu01:
    dataRef: Health gl-ep-stb-hem-avpu01
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-stb-hem-avpu01:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-stb-hem-avpu01&var-encoder=$__all"
      params: "none"
      sameTab: false  
  encoderHealth_gl-ep-stb-hem-avpu02:
    dataRef: Health gl-ep-stb-hem-avpu02
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  encoderIcon_gl-ep-stb-hem-avpu02:
    link:
      url: "https://gl1.grafana.net/d/yu8wqtx4321/encoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-ep-stb-hem-avpu02&var-encoder=$__all"
      params: "none"
      sameTab: false  

#---------------------------------------------SWITCHES--------------------------------------------
  switchHealth_gl-ep-bxl-jan-sw01:
    dataRef: Switch Health {hostname="gl-ep-bxl-jan-sw01", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  switchIcon_gl-ep-bxl-jan-sw01:
    link:
      url: "https://gl1.grafana.net/d/yuv5x84fefe/backend-switches-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-jan-sw01&var-BSW=Routing%20Engine%200"
      params: "none"
      sameTab: false  
  switchHealth_gl-ep-bxl-jan-sw02:
    dataRef: Switch Health {hostname="gl-ep-bxl-jan-sw01", sensor_descr="Routing Engine 1"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  switchIcon_gl-ep-bxl-jan-sw02:
    link:
      url: "https://gl1.grafana.net/d/yuv5x84fefe/backend-switches-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-jan-sw01&var-BSW=Routing%20Engine%201"
      params: "none"
      sameTab: false  
  switchHealth_gl-ep-bxl-phs-hem-sw01:
    dataRef: Switch Health {hostname="gl-ep-bxl-phs-hem-sw01", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  switchIcon_gl-ep-bxl-phs-hem-sw01:
    link:
      url: "https://gl1.grafana.net/d/yuv5x84fefe/backend-switches-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-phs-hem-sw01&var-BSW=Routing%20Engine%200"
      params: "none"
      sameTab: false  
  switchHealth_gl-ep-bxl-phs-hem-sw02:
    dataRef: Switch Health {hostname="gl-ep-bxl-phs-hem-sw01", sensor_descr="Routing Engine 1"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  switchIcon_gl-ep-bxl-phs-hem-sw02:
    link:
      url: "https://gl1.grafana.net/d/yuv5x84fefe/backend-switches-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-phs-hem-sw01&var-BSW=Routing%20Engine%201"
      params: "none"
      sameTab: false  
  switchHealth_gl-ep-stb-phs-hem-sw01:
    dataRef: Switch Health {hostname="gl-ep-stb-hem-sw01", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  switchIcon_gl-ep-stb-phs-hem-sw01:
    link:
      url: "https://gl1.grafana.net/d/yuv5x84fefe/backend-switches-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-stb-hem-sw01&var-BSW=Routing%20Engine%200"
      params: "none"
      sameTab: false  
  switchHealth_gl-ep-stb-phs-hem-sw02:
    dataRef: Switch Health {hostname="gl-ep-stb-hem-sw01", sensor_descr="Routing Engine 1"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  switchIcon_gl-ep-stb-phs-hem-sw02:
    link:
      url: "https://gl1.grafana.net/d/yuv5x84fefe/backend-switches-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-stb-hem-sw01&var-BSW=Routing%20Engine%201"
      params: "none"
      sameTab: false  

#---------------------------------------------FIREWALL--------------------------------------------
  firewallHealth_gl-ep-bxl-jan-fw01:
    dataRef: Network Device Health {hostname="gl-ep-bxl-fw", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  firewallIcon_gl-ep-bxl-jan-fw01:
    link:
      url: "https://gl1.grafana.net/d/fek6xzsefs/firewalls-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-fw"
      params: "none"
      sameTab: false  
  firewallHealth_gl-ep-bxl-phs-hem-fw01:
    dataRef: Network Device Health {hostname="gl-ep-bxl-fw", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  firewallIcon_gl-ep-bxl-phs-hem-fw01:
    link:
      url: "https://gl1.grafana.net/d/fek6xzsefs/firewalls-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-fw"
      params: "none"
      sameTab: false  
  firewallHealth_gl-ep-stb-phs-hem-fw01:
    dataRef: Network Device Health {hostname="gl-ep-stb-fw", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  firewallIcon_gl-ep-stb-phs-hem-fw01:
    link:
      url: "https://gl1.grafana.net/d/fek6xzsefs/firewalls-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-stb-fw"
      params: "none"
      sameTab: false  
  firewallHealth_gl-ep-stb-phs-hem-fw02:
    dataRef: Network Device Health {hostname="gl-ep-stb-fw", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  firewallIcon_gl-ep-stb-phs-hem-fw02:
    link:
      url: "https://gl1.grafana.net/d/fek6xzsefs/firewalls-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-stb-fw"
      params: "none"
      sameTab: false  

#----------------------------------------FRONTEND SWITCHES-------------------------------------------------
  frontendSwitchHealth_gl-ep-bxl-jan-fsw01:
    dataRef: Switch Health {hostname="gl-ep-bxl-fsw01", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  frontendSwitchIcon_gl-ep-bxl-jan-fsw01:
    link:
      url: "https://gl1.grafana.net/d/ferf476ada21/frontend-switch-overview-draft?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-fsw01&var-FSW=Routing%20Engine%200"
      params: "none"
      sameTab: false  
  frontendSwitchHealth_gl-ep-bxl-phs-hem-fsw01:
    dataRef: Switch Health {hostname="gl-ep-bxl-fsw01", sensor_descr="Routing Engine 1"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  frontendSwitchIcon_gl-ep-bxl-phs-hem-fsw01:
    link:
      url: "https://gl1.grafana.net/d/ferf476ada21/frontend-switch-overview-draft?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-bxl-fsw01&var-FSW=Routing%20Engine%201"
      params: "none"
      sameTab: false  
  frontendSwitchHealth_gl-ep-stb-phs-hem-fsw01:
    dataRef: Switch Health {hostname="gl-ep-stb-fsw01", sensor_descr="Routing Engine 0"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  frontendSwitchIcon_gl-ep-stb-phs-hem-fsw01:
    link:
      url: "https://gl1.grafana.net/d/ferf476ada21/frontend-switch-overview-draft?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-stb-fsw01&var-FSW=Routing%20Engine%200"
      params: "none"
      sameTab: false  
  frontendSwitchHealth_gl-ep-stb-phs-hem-fsw02:
    dataRef: Switch Health {hostname="gl-ep-stb-fsw01", sensor_descr="Routing Engine 1"}
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  frontendSwitchIcon_gl-ep-stb-phs-hem-fsw02:
    link:
      url: "https://gl1.grafana.net/d/ferf476ada21/frontend-switch-overview-draft?orgId=1&from=now-6h&to=now&timezone=browser&var-Hostname=gl-ep-stb-fsw01&var-FSW=Routing%20Engine%201"
      params: "none"
      sameTab: false  

#-------------------------------------------TRANSCODERS----------------------------------------------
  transcoderHealth_gl-dus-k3s-01:
    dataRef: Health gl-dus-k3s-01
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  transcoderIcon_gl-dus-k3s-01:
    link:
      url: "https://gl1.grafana.net/d/yu67v94wf4/trancoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-dus-k3s-01&var-transcoder=$__all"
      params: "none"
      sameTab: false
  transcoderHealth_gl-dus-k3s-02:
    dataRef: Health gl-dus-k3s-02
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  transcoderIcon_gl-dus-k3s-02:
    link:
      url: "https://gl1.grafana.net/d/yu67v94wf4/trancoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-dus-k3s-02&var-transcoder=$__all"
      params: "none"
      sameTab: false
  transcoderHealth_gl-fra-k3s-01:
    dataRef: Health gl-fra-k3s-01
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  transcoderIcon_gl-fra-k3s-01:
    link:
      url: "https://gl1.grafana.net/d/yu67v94wf4/trancoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-fra-k3s-01&var-transcoder=$__all"
      params: "none"
      sameTab: false
  transcoderHealth_gl-fra-k3s-02:
    dataRef: Health gl-fra-k3s-02
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
        - { color: "orange", level: 2 }
  transcoderIcon_gl-fra-k3s-02:
    link:
      url: "https://gl1.grafana.net/d/yu67v94wf4/trancoders-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-cluster=gl-fra-k3s-02&var-transcoder=$__all"
      params: "none"
      sameTab: false
#---------------------------------------------HSG SRT------------------------------------------------
  HSG-SRT-Health_dus:
    dataRef: "HSG SRT Health https://hsg-dus.gl-systemhaus.de"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "gray", level: 0 }
        - { color: "red", level: 1 }
        - { color: "yellow", level: 2 }
        - { color: "green", level: 3 }
  HSG-SRT-Icon_dus:
    link:
      url: "https://gl1.grafana.net/d/1a67019f-4780-47a5-aec5-6519ac9887b5/haivision-srt-gateways-draft??orgId=1&from=now-3h&to=now&timezone=browser&var-datasource=ddeugnc9e6nswa&var-gateway=https:%2F%2Fhsg-dus.gl-systemhaus.de&var-routes=HSE24&var-routes=bxl-01&var-routes=bxl-02&var-routes=bxl-03&var-routes=bxl-04&var-routes=bxl-05&var-routes=bxl-06&var-routes=bxl-07&var-routes=bxl-08&var-routes=bxl-09&var-routes=bxl-10&var-routes=bxl-11&var-routes=bxl-12&var-routes=bxl-13&var-routes=bxl-14&var-routes=bxl-15&var-routes=bxl-16&var-routes=bxl-17&var-routes=bxl-18&var-routes=bxl-19&var-routes=bxl-20&var-routes=bxl-hem-01&var-routes=bxl-hem-02&var-routes=bxl-hem-03&var-routes=bxl-hem-04&var-routes=stb-hem-01&var-routes=stb-hem-02&var-routes=stb-hem-03&var-routes=stb-hem-04&var-routes=stb-hem-05&var-routes=stb-hem-06&var-routes=stb-hem-07&var-routes=stb-hem-08&refresh=1m"
      params: "none"
      sameTab: false
  HSG-SRT-Health_ffm:
    dataRef: "HSG SRT Health https://hsg-ffm.gl-systemhaus.de"
    fillColor:
      gradientMode: "fixed"
      thresholds:
        - { color: "gray", level: 0 }
        - { color: "red", level: 1 }
        - { color: "yellow", level: 2 }
        - { color: "green", level: 3 }
  HSG-SRT-Icon_ffm:
    link:
      url: "https://gl1.grafana.net/d/1a67019f-4780-47a5-aec5-6519ac9887b5/haivision-srt-gateways-draft?orgId=1&from=now-3h&to=now&timezone=browser&var-datasource=ddeugnc9e6nswa&var-gateway=https:%2F%2Fhsg-ffm.gl-systemhaus.de&var-routes=HSE24&var-routes=bxl-01&var-routes=bxl-02&var-routes=bxl-03&var-routes=bxl-04&var-routes=bxl-05&var-routes=bxl-06&var-routes=bxl-07&var-routes=bxl-08&var-routes=bxl-09&var-routes=bxl-10&var-routes=bxl-11&var-routes=bxl-12&var-routes=bxl-13&var-routes=bxl-14&var-routes=bxl-15&var-routes=bxl-16&var-routes=bxl-17&var-routes=bxl-18&var-routes=bxl-19&var-routes=bxl-20&var-routes=bxl-hem-01&var-routes=bxl-hem-02&var-routes=bxl-hem-03&var-routes=bxl-hem-04&var-routes=stb-hem-01&var-routes=stb-hem-02&var-routes=stb-hem-03&var-routes=stb-hem-04&var-routes=stb-hem-05&var-routes=stb-hem-06&var-routes=stb-hem-07&var-routes=stb-hem-08&refresh=1m"
      params: "none"
      sameTab: false